apiVersion: multicloud.aether.io/v1alpha1
kind: S3Bucket
metadata:
  name: s3bucket2-aether
spec:
  parameters:
    location: us-east-1
  compositionSelector:
    matchLabels:
      type: s3
      provider: aws 
  writeConnectionSecretToRef:
    name: s3bucket-aws-conn